### PR TITLE
feat: Update class safelist for darkmode support

### PR DESCRIPTION
**Pull request by mattbearman**
This safelist is used to generate tailwind classes that cannot be inferred from the code, ie: where `Shard::Colors.variant` and `Shard::Colors.variants` are used.

Having to keep the updated manually is not an ideal solution, but for now it works, I'll be raising a ticket to investigate ways of populating this automatically.

The easiest way to test this locally is to copy the `safelist` array from this PR into `demo/tailwind.config.js` in the main shard repo and then run the demo. At this stage you'll be doing a regression test to ensure I haven't broken any of the existing components 😅 

Although it should be pretty clear from the diff that this only adds new patterns and doesn't affect any existing ones 👍

### CODE REVIEW

**Comment by mattbearman** [comment]
@andrewjtait @naft-a hold off on reviewing this please, I just found some more I'll probably need to add 😅

**Comment by mattbearman** [comment]
@andrewjtait @naft-a _now_ this is ready for review

**Comment by andrewjtait** [comment]
> I'll be raising a ticket to investigate ways of populating this automatically.

I think the easiest way to resolve this is to not rely on it at all 😅 are the colour helpers _that_ useful?

**Review by andrewjtait — APPROVED** [review]
Seems okay to me! I ran the precompile task locally, and it added 20kb to the uncompressed asset, and 1kb to the compressed one. Which I guess is fine for adding a new colour set for a theme!

It's not an ideal process though, as you've mentioned in your PR description. It still includes a whole lot of classes we don't use.

**Pull request merged**
